/***************************************************************************//**
 * @file
 * @brief General Purpose IO (GPIO) peripheral API for the TDxxxx RF modules.
 * @author Telecom Design S.A.
 * @version 2.1.0
 ******************************************************************************
 * @section License
 * <b>(C) Copyright 2012-2014 Telecom Design S.A., http://www.telecomdesign.fr</b>
 ******************************************************************************
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must not
 *    claim that you wrote the original software.
 * 2. Altered source versions must be plainly marked as such, and must not be
 *    misrepresented as being the original software.
 * 3. This notice may not be removed or altered from any source distribution.
 *
 * DISCLAIMER OF WARRANTY/LIMITATION OF REMEDIES: Telecom Design SA has no
 * obligation to support this Software. Telecom Design SA is providing the
 * Software "AS IS", with no express or implied warranties of any kind,
 * including, but not limited to, any implied warranties of merchantability
 * or fitness for any particular purpose or warranties against infringement
 * of any proprietary rights of a third party.
 *
 * Telecom Design SA will not be liable for any consequential, incidental, or
 * special damages, or any other relief, or for any claim by any third party,
 * arising from your use of this Software.
 *
  ******************************************************************************/

#include <stdint.h>
#include <stdbool.h>

#include <em_cmu.h>
#include <em_gpio.h>

#include "td_core.h"
#include "td_gpio.h"
#include "td_utils.h"
#include "td_rtc.h"
#include "td_printf.h"

/***************************************************************************//**
 * @addtogroup GPIO
 * @brief General Purpose IO (GPIO) peripheral API for the TDxxxx RF modules
 * @{
 ******************************************************************************/

/*******************************************************************************
 **************************   PUBLIC VARIABLES   *******************************
 ******************************************************************************/

/** @addtogroup GPIO_GLOBAL_VARIABLES Global Variables
 * @{ */

/** Callback array */
TD_GPIO_callback_t TD_GPIO_CallbackInterrupts[16];

/** @} */

#ifdef __ICCARM__
#pragma optimize = speed
#else
#pragma GCC optimize ("O3")
#endif

/*******************************************************************************
 **************************  PRIVATE FUNCTIONS   *******************************
 ******************************************************************************/

/** @addtogroup WATCHDOG_LOCAL_FUNCTIONS Local Functions
 * @{ */

/***************************************************************************//**
 * @brief
 *   Dispatch an interrupt to the registered callback functions.
 *
 * @param[in] flag
 *   The binary interrupt flag to check for dispatching.
 ******************************************************************************/
static void InterruptDispatch(uint32_t flag)
{
	int i;

	for (i = 0; i < 16; i++) {
		if ((1 << i) & flag) {
			if (TD_GPIO_CallbackInterrupts[i] != 0) {
				(*TD_GPIO_CallbackInterrupts[i])(1 << i);
			}
			TD_WakeMainLoop();
		}
	}
}

/** @} */

/*******************************************************************************
 **************************   PUBLIC FUNCTIONS   *******************************
 ******************************************************************************/

/** @addtogroup GPIO_USER_FUNCTIONS User Functions
 * @{ */

/***************************************************************************//**
 * @brief
 *   GPIO odd interrupt handler
 *
 * @details
 *   This function is automatically called by the hardware upon incoming
 *   interrupt generated by an odd-numbered GPIO pin.
 ******************************************************************************/
void GPIO_ODD_IRQHandler(void)
{
	uint32_t flag;

	// Get interrupt bits
	flag = (GPIO_IntGet() & TD_GPIO_ODD_MASK) & GPIO_IntGetEnabled();

	// Acknowledge IRQ
	// We acknowledge all IRQ read, for this IRQ (EVEN) and enabled
	// even if theses IRQ are not used (otherwise, it will infinitely reenter in
	// this IRQ)
	GPIO_IntClear(flag);

#ifdef WAKE_MAIN_LOOP_DEBUG
	tfp_printf("IO:0x%08X\r\n");
#endif

	InterruptDispatch(flag);
}

/***************************************************************************//**
 * @brief
 *   GPIO even interrupt handler
 *
 * @details
 *   This function is automatically called by the hardware upon incoming
 *   interrupt generated by an even-numbered GPIO pin.
 ******************************************************************************/
void GPIO_EVEN_IRQHandler(void)
{
	uint32_t flag;

	// Get interrupt bits
	flag = GPIO_IntGet() & TD_GPIO_EVEN_MASK & GPIO_IntGetEnabled();

	// Acknowledge IRQ.
	// We acknowledge all IRQ read, for this IRQ (EVEN) and enabled
	// even if theses IRQ are not used (otherwise, it will infinitely reenter in
	// this IRQ)
	GPIO_IntClear(flag);
#ifdef WAKE_MAIN_LOOP_DEBUG
	tfp_printf("IO:0x%08X\r\n");
#endif

	InterruptDispatch(flag);
}

/***************************************************************************//**
 * @brief
 *  Append a callback for this interrupt
 *
 * @param bit
 *  Bit value for input pin. Should be <= 15
 *
 * @param callback
 *  Callback to call on interrupt event
 *
 * @return
 *  return overriden callback.
 ******************************************************************************/
TD_GPIO_callback_t TD_GPIO_SetCallbackExtended(uint8_t bit,
	TD_GPIO_callback_t callback)
{
	TD_GPIO_callback_t previous;

	if (bit > 15) {
		return 0;
	}
	previous = TD_GPIO_CallbackInterrupts[bit];
	TD_GPIO_CallbackInterrupts[bit] = callback;
	return previous;
}

/***************************************************************************//**
 * @brief
 *   Register a callback function for processing interrupts matching a given bit
 *   mask.
 *   Depreciated. Please use TD_GPIO_SetCallbackExtended instead.
 *
 * @param[in] type
 *   The type of callback to set up.
 *
 * @param[in] callback
 *   Pointer to callback function called when an interrupt matching the mask is
 *   received.
 *
 * @param[in] mask
 *   Mask for testing a received even interrupts against.
 ******************************************************************************/
void TD_GPIO_SetCallback(int type, TD_GPIO_callback_t callback, uint32_t mask)
{
	uint8_t start;

	if (type < TD_GPIO_ODD) {

		 // Even
		start = 0;
	} else {

		// Odd
		start = 1;
	}

	// Set callback for all odd or even IOs
	for (; start < 16; start += 2) {

		// If set callback, only apply to masked interrupt
		// If unset callback, remove all interrupt
		if (callback == 0 || (callback != 0 && ((1 << start)& mask))) {
			TD_GPIO_SetCallbackExtended(start, callback);
		}
	}
}

/***************************************************************************//**
 * @brief
 *   Overload GPIO_PinModeSet to allow driving:
 *   - EFM32 pin
 *   - Radio pin
 *   - No pin
 ******************************************************************************/
void TD_GPIO_PinModeSet(TD_GPIO_Port_TypeDef port, unsigned int bit,
	GPIO_Mode_TypeDef mode, unsigned int out)
{
	uint8_t value;

	if (port == TD_GPIO_PortNull) {
		return;
	} else if (port == TD_GPIO_PortRadio) {
		if (bit > 3) {
			return;
		}
		value = out;
		switch(mode) {
		case gpioModeDisabled:
			TD_RF_GPIO_PinConfigure(bit, TD_RF_GPIO_DISABLED, &value);
			break;

		case gpioModePushPull:
		case gpioModePushPullDrive:
			TD_RF_GPIO_PinConfigure(bit, TD_RF_GPIO_OUTPUT, &value);
			break;

		default:
			break;
		}
	} else {
		GPIO_PinModeSet((GPIO_Port_TypeDef) port, bit, mode, out);
	}
}

/***************************************************************************//**
 * @brief
 *   Overload GPIO_DriveModeSet to allow driving:
 *   - EFM32 pin
 *   - Radio pin
 *   - No pin
 ******************************************************************************/
void TD_GPIO_DriveModeSet(TD_GPIO_Port_TypeDef port, GPIO_DriveMode_TypeDef mode)
{
	if (port != TD_GPIO_PortNull && port != TD_GPIO_PortRadio) {
		GPIO_DriveModeSet((GPIO_Port_TypeDef) port, mode);
	}
}

/***************************************************************************//**
 * @brief
 *   Initialize the GPIO peripheral for the TDxxxx RF modules.
 ******************************************************************************/
void TD_GPIO_Init(void)
{

	// Enable the GPIO module clock
	CMU_ClockEnable(cmuClock_GPIO, true);

	// Start LFXO and wait until it is stable
	CMU_OscillatorEnable(cmuOsc_LFXO, true, true);

	// Initialize IRQ hooks
	memset(TD_GPIO_CallbackInterrupts, 0, sizeof (TD_GPIO_callback_t) * 16);

	// Init nvic interrupt
	NVIC_EnableIRQ(GPIO_EVEN_IRQn);
	NVIC_EnableIRQ(GPIO_ODD_IRQn);
}

/***************************************************************************//**
 * @brief
 *   Dump all GPIO configuration
 ******************************************************************************/
void TD_GPIO_Dump(void)
{
	uint8_t i, j, md;
	uint64_t mode;
	uint32_t d;
	static char const str[][6] = {
		"DIS", "IN", "INP", "INPF", "OUT", "OUTD",
		"WOR", "WORP", "WAN", "WANF", "WANP", "WANPF",
		"WAND", "WANDF", "WANDP", "WADPF"
	};
	static char const str_drive[][6] = {
		"STAND","LOWES"," HIGH"," LOW "
	};
	for (i = 0; i < 6; i++) {
		tfp_printf("--Port%c Drive:%s--\r\n", 'A' + i,
			str_drive[GPIO->P[i].CTRL&3]);
		mode = GPIO->P[i].MODEL;
		mode = mode | (((uint64_t)GPIO->P[i].MODEH) << 32);
		d = GPIO->P[i].DOUT;
		for (j = 0; j < 16; j++) {
			md = mode & 0xF;
			mode = mode >> 4;
			tfp_printf("%01X)%6s:%d|  ", j, &str[md][0], d & 1);
			d >>= 1;
			if ((j & 3) == 3) {
				tfp_printf("\r\n");
			}
		}
	}
}
/** @} */

/** @} (end addtogroup GPIO) */
